language: python
sudo: false
python:
  - '2.6'
  - '2.7'

before_install:
  - pip install -r dev-requirements.txt
  - if ! [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install twisted; fi

install:
  python setup.py install


script: ./run-tests.sh
